<?php
namespace app\base;

use app\components\RbacComponent;
use yii\base\Action;

class BaseController extends \yii\web\Controller
{
    /**
     * @var $rbac RbacComponent
     */
    public $rbac;

    public function init()
    {
        $this->rbac = \Yii::$app->rbac;
        parent::init(); // TODO: Change the autogenerated stub
    }


    protected function getRbac(){
        return \Yii::$app->rbac;
    }



    /**
     * @param $action Action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        //TODO: redirect to auth
        if(\Yii::$app->user->isGuest){
            //throw new HttpException(401,'Need authorization');
            return \Yii::$app->runAction('/auth/login');
        }
        return parent::beforeAction($action);
    }

}